# Generated by Django 5.2.6 on 2025-09-25 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_enseignant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignant',
            name='matricule',
        ),
    ]
