# Generated by Django 5.2.6 on 2025-10-13 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_matiere_enseignant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='niveau',
            name='matieres',
        ),
        migrations.AddField(
            model_name='matiere',
            name='niveau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='notes.niveau'),
        ),
    ]
