# Generated by Django 5.2.6 on 2025-10-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_alter_eleve_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='matricule',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
