# Generated by Django 5.2.6 on 2025-10-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_alter_eleve_matricule'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='matieres',
            field=models.ManyToManyField(blank=True, to='notes.matiere', verbose_name='Sélectionner les matières suivies (laisser vide pour auto-associer selon le niveau)'),
        ),
    ]
